### ISSUE TITLE
Flask project integration?

### ISSUE THREAD

**Issue by jezdez** [cenkalti/kuyruk-manager#1]
Hi @cenkalti, I'm trying to figure out a way how to integrate this into an existing Flask project and wondered why there is a separate daemon thread that uses RPyC to call to the manager process. E.g. is there a way to have the same managing UI without that dependency and need to run as a separate process?

**Comment by cenkalti** [comment]
Hello @jezdez, the reason for separate RPC thread is that the manager needs a connection to each worker to be able to send them control commands such as (shutdown worker, abort worker, drop current task).

The manager itself is a Flask app, I can convert it to a Flask Blueprint easily to make it possible to integrate with existing applications. However, if your application is running on multiple servers, you need to make sure that all workers connect to the same server.

What do you think?

**Comment by jezdez** [comment]
@cenkalti Aha, that makes sense, thank you for clarifying. I think having a blueprint would be useful, but I admit it's an edge case and may not be useful in general. I'm happy to test drive it though if you need help.

**Comment by cenkalti** [comment]
I have exported a Flask Blueprint from Kuyruk Manager class:

https://github.com/cenkalti/kuyruk-manager/blob/86c87b631f74780bc333142a79a0b7a6e422206c/kuyruk_manager/__init__.py#L94
